{% set version = "1.0.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gganimate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gganimate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gganimate/gganimate_{{ version }}.tar.gz
  sha256: bfca4c0c085933a1d97dd6c3b02f64049e1b722ed8fa9bf14880c0938e9fd604

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli
    - r-ggplot2 >=3.5.0
    - r-glue
    - r-lifecycle
    - r-progress
    - r-rlang
    - r-scales
    - r-stringi
    - r-transformr >=0.1.5
    - r-tweenr >=2.0.3
    - r-vctrs
  run:
    - r-base
    - r-cli
    - r-ggplot2 >=3.5.0
    - r-glue
    - r-lifecycle
    - r-progress
    - r-rlang
    - r-scales
    - r-stringi
    - r-transformr >=0.1.5
    - r-tweenr >=2.0.3
    - r-vctrs

test:
  commands:
    - $R -e "library('gganimate')"           # [not win]
    - "\"%R%\" -e \"library('gganimate')\""  # [win]

about:
  home: http://github.com/thomasp85/gganimate
  license: MIT
  summary: The grammar of graphics as implemented in the 'ggplot2' package has been successful in providing a powerful API for creating static  visualisation. In order to extend the API for animated graphics this package provides a completely new set of grammar, fully compatible with 'ggplot2'  for specifying transitions
    and animations in a flexible and extensible way.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
