appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ivfyqYQAI/XrMpmf7ZYIfGA34Oes0muTV+UWJRxaS2c3pmZEgAfcv7kbTUJB0DeQWnC/ZCihKc6ni76KmVCvfogKndBmQlo7kEoauwi2zCeiEIqqWlvL46L9HQpJhqs9JxClopOp3L1r6SGpeRh9BSfnfs3O34cbVk1X7nYBzEY8q9nyTd6YkO3dNqhf+vXnMgOXuSgyIMPw/d2RSc38QfqWNdwXddOx5GeNFWtyGK8ki/LgkEJwRtRU2QearKuwhz/lXhVQmiuxXKxqRzpiXBx347E+wXwTjnBgqX9rev4+x4bTUz9VqGxw9H6NFNORi/tcLCFx3uSOyDQFM/PtzP3GwBqB3rtNgIR07NN/zL95HGESNv6cNL2nzZLx6aRQ/rEmGPqQEb8quQbMaAEgCxvRy+c6HM3NAaBTPMI2zx+WFp/4RnGRbZlhM3mZ0vvB46PCkVg1cREixx34f8qXLsGpVYfrxuMRhcjpBaZqMnke44MJR6I3+rqB3NhmACsxrWkc9R65Swu+SqX43BlEATiILLlVxSYkpTaurWVUoVR6oegG29xtoAi1Szve6eZ9T+c1KQ4Vj1wadWFH+lnzS/isINBucltIApzjyMu6WIBiwdbvB4QxkUFwYn6kd6baE85tv5/ClQ0hWxNeY+NO2YBnvE+cg44emQMjQ1Igjqg=
conda_forge_output_validation: true
